import pygame
import math
import sys

import random

pygame.init()
screenWidth = 800
screenHeight = 800
screen = pygame.display.set_mode((screenWidth, screenHeight))
pygame.display.set_caption("JumpShot")

#fps display
clock = pygame.time.Clock()
def displayFPS(screen, fontSize):
    font = pygame.font.SysFont(None, fontSize)
    fps = int(clock.get_fps())
    fps_text = font.render(f"FPS: {fps}", True, (0, 0, 0))
    screen.blit(fps_text, (10, 10))

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

def linenItersection(p1, p2, p3, p4, inSegments):
    #math generated by ChatGPT

    x1, y1 = p1
    x2, y2 = p2
    x3, y3 = p3
    x4, y4 = p4

    # Calculate the denominators
    denom = (y4 - y3)*(x2 - x1) - (x4 - x3)*(y2 - y1)
    if denom == 0:
        # Lines are parallel or coincident
        return None

    # Calculate the numerators
    ua = ((x4 - x3)*(y1 - y3) - (y4 - y3)*(x1 - x3)) / denom

    # Get final point coordinates
    x = x1 + ua * (x2 - x1)
    y = y1 + ua * (y2 - y1)

    # Check if point is on line segments
    if inSegments:
        ub = ((x2 - x1)*(y1 - y3) - (y2 - y1)*(x1 - x3)) / denom
        if 0 <= ua <= 1 and 0 <= ub <= 1:
            return (x, y)
        else:
            return None
    
    return (x, y)

# - - - - - - - - - - - - - - - - - - - - - - - -  - - - - - - - - - - - - - - -

class Player():
    def __init__(self, pos):
        self.pos = pos

        self.vel = (0, 0)
        self.gravity = (0, 0.5)
        self.gunForce = 15

        self.shotsLeft = 10
        self.score = 0

        #sprite stuff
        self.angle = 0
        self.shadowYoffset = 15
        self.originalImage = pygame.image.load("Assets/shotgun_white.png").convert_alpha()
        self.originalImage = pygame.transform.scale(self.originalImage, (150, 150 * 0.2616))
        self.image = self.originalImage
        self.rect = self.image.get_rect(center=(self.pos[0], self.pos[1]))

        #shadowstuff
        self.originalImage_shdw = pygame.image.load("Assets/shotgun_shadow.png").convert_alpha()
        self.originalImage_shdw = pygame.transform.scale(self.originalImage_shdw, (150, 150 * 0.2616))
        self.image_shdw = self.originalImage_shdw
        self.rect_shdw = self.image_shdw.get_rect(center=(self.pos[0], self.pos[1] + self.shadowYoffset))

    def draw(self):
        #get angle to moue
        x1, y1 = self.pos
        x2, y2 = pygame.mouse.get_pos()

        dx = x2 - x1
        dy = y2 - y1

        angle_rad = math.atan2(dy, dx)
        angle_deg = math.degrees(angle_rad)
        self.angle = angle_deg

        self.image = pygame.transform.rotate(self.originalImage, -self.angle)
        self.rect = self.image.get_rect()
        self.rect.centerx = self.pos[0]
        self.rect.centery = self.pos[1]

        self.image_shdw = pygame.transform.rotate(self.originalImage_shdw, -self.angle)
        self.rect_shdw = self.image_shdw.get_rect()
        self.rect_shdw.centerx = self.pos[0]
        self.rect_shdw.centery = self.pos[1] + self.shadowYoffset

        #blit order
        screen.blit(self.image_shdw, self.rect_shdw)
        screen.blit(self.image, self.rect)

    def physicsUpdate(self):

        #apply gravity accelaration
        self.vel = (self.vel[0], self.vel[1] + self.gravity[1])

        #apply velocity
        self.pos = (self.pos[0] + self.vel[0], self.pos[1] + self.vel[1])

        #bounce of edges
        if self.pos[0] < 0:
            self.pos = (0, self.pos[1])
            self.vel = (self.vel[0] * -1, self.vel[1])
        if self.pos[0] > screenWidth:
            self.pos = (screenWidth, self.pos[1])
            self.vel = (self.vel[0] * -1, self.vel[1])

    def shoot(self):
        #do knockback

        #get to mouse direction
        mPos = pygame.mouse.get_pos()
        vecToMouse = (mPos[0] - self.pos[0], mPos[1] - self.pos[1])
        oppositeVec = (vecToMouse[0] * -1, vecToMouse[1] * -1)
        mag = math.sqrt(oppositeVec[0] ** 2 + oppositeVec[1] ** 2)
        normalizedVec = (oppositeVec[0] / mag, oppositeVec[1] / mag)

        #apply opposite force by gunForce
        self.vel = (normalizedVec[0] * self.gunForce, normalizedVec[1] * self.gunForce)

        #check clay shots using line intersections
        #do 6 spread lines from gun and check intersections with clays
        shotAngles = []
        spreadAngle = 30
        for i in range(24):
            shotAngle = -spreadAngle/2 + i * (spreadAngle/24)
            shotAngles.append(shotAngle)

        numOfClaysShot = 0
        for i in range(len(shotAngles)):
            shotAngle = self.angle + shotAngles[i]

            #get shot points
            s1 = self.pos
            angle_rad = math.radians(shotAngle)
            s2 = (s1[0] + math.cos(angle_rad) * 1200, s1[1] + math.sin(angle_rad) * 1200)

            #pygame.draw.line(screen, (255, 0, 0), s1, s2, 4)

            for j in range(len(clays)):
                #get 2 lines crossing the clay to get a "hitbox"
                clay = clays[j]
                p1 = (clay.pos[0] - 30, clay.pos[1])
                p2 = (clay.pos[0] + 30, clay.pos[1])
                p3 = (clay.pos[0], clay.pos[1] - 30)
                p4 = (clay.pos[0], clay.pos[1] + 30)

                #check if lines intersect
                doesIntersect = False
                in1 = linenItersection(s1, s2, p1, p2, True)
                in2 = linenItersection(s1, s2, p3, p4, True)
                if in1 != None and in2 != None:
                    doesIntersect = True

                if doesIntersect and clay.hasBeenShot == False:
                    numOfClaysShot += 1
                    clay.hasBeenShot = True
                    clay.isDead = True

        self.shotsLeft += 2 * numOfClaysShot
        self.score += numOfClaysShot

class Clay():
    def __init__(self, pos):
        clays.append(self)
        self.pos = pos

        self.vel = (0, 0)
        self.gravity = (0, 0.5)

        self. angle = 0
        self.angleVel = 0

        self.isDead = False
        self.hasBeenShot = False

        #sprite stuff
        self.angle = 0
        self.shadowYoffset = 15
        self.originalImage = pygame.image.load("Assets/target_white.png").convert_alpha()
        self.originalImage = pygame.transform.scale(self.originalImage, (60, 60))
        self.image = self.originalImage
        self.rect = self.image.get_rect(center=(self.pos[0], self.pos[1]))

        #shadowstuff
        self.originalImage_shdw = pygame.image.load("Assets/target_shadow.png").convert_alpha()
        self.originalImage_shdw = pygame.transform.scale(self.originalImage_shdw, (60, 60))
        self.image_shdw = self.originalImage_shdw
        self.rect_shdw = self.image_shdw.get_rect(center=(self.pos[0], self.pos[1] + self.shadowYoffset))

    def draw(self):
        self.angle += self.angleVel

        self.image = pygame.transform.rotate(self.originalImage, -self.angle)
        self.rect = self.image.get_rect()
        self.rect.centerx = self.pos[0]
        self.rect.centery = self.pos[1]

        self.image_shdw = pygame.transform.rotate(self.originalImage_shdw, -self.angle)
        self.rect_shdw = self.image_shdw.get_rect()
        self.rect_shdw.centerx = self.pos[0]
        self.rect_shdw.centery = self.pos[1] + self.shadowYoffset

        #blit order
        screen.blit(self.image_shdw, self.rect_shdw)
        screen.blit(self.image, self.rect)

    def physicsUpdate(self):

        #apply gravity accelaration
        self.vel = (self.vel[0], self.vel[1] + self.gravity[1])

        #apply velocity
        self.pos = (self.pos[0] + self.vel[0], self.pos[1] + self.vel[1])

# - - - - - -

#load images
originalImage = pygame.image.load("Assets/background2.png").convert_alpha()
originalImage = pygame.transform.scale(originalImage, (screenWidth, screenHeight))
image = originalImage
rect = image.get_rect(center=(screenWidth/2, screenHeight/2))

#shells
shellsImage = pygame.image.load("Assets/shells_white.png").convert_alpha()
shellsImage = pygame.transform.scale(shellsImage, (70, 60))
shellsImageProccessed = shellsImage
rect1 = shellsImageProccessed.get_rect(center=(1/4 * screenWidth, screenHeight/2 - 120))

shellsImageS = pygame.image.load("Assets/shells_shadow.png").convert_alpha()
shellsImageS = pygame.transform.scale(shellsImageS, (70, 60))
shellsImageProccessedS = shellsImageS
rect1S = shellsImageProccessedS.get_rect(center=(1/4 * screenWidth, screenHeight/2 - 110))

#targets
targetsImage = pygame.image.load("Assets/target_white.png").convert_alpha()
targetsImage = pygame.transform.scale(targetsImage, (60, 60))
targetsImageProccessed = targetsImage
rect2 = targetsImageProccessed.get_rect(center=(3/4 * screenWidth, screenHeight/2 - 120))

targetsImageS = pygame.image.load("Assets/target_shadow.png").convert_alpha()
targetsImageS = pygame.transform.scale(targetsImageS, (60, 60))
targetsImageProccessedS = targetsImageS
rect2S = targetsImageProccessedS.get_rect(center=(3/4 * screenWidth, screenHeight/2 - 110))

def drawBackground():
    screen.blit(image, rect)
    screen.blit(shellsImageProccessedS, rect1S)
    screen.blit(targetsImageProccessedS, rect2S)
    screen.blit(shellsImageProccessed, rect1)
    screen.blit(targetsImageProccessed, rect2)

def spawnClay():
    rand = random.randint(0, 1)
    pos = [(-50, 700 - random.randint(0, 80)), (screenWidth + 50, 700 - random.randint(0, 80))][rand]
    vel = [(12, -10), (-12, -10)][rand]
    angleVel = random.uniform(-90, 90)

    newClay = Clay(pos)
    newClay.vel = vel
    newClay.angleVel = 0

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

plyr = Player((400, 200))

clays = []
clayReqCooldown = 0 * 60
clayCurrCooldown = 0

font = pygame.font.SysFont(None, 90)
fps = int(clock.get_fps())

running = True
while running:

    screen.fill((0, 0, 0))
    drawBackground()

    #events
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        elif event.type == pygame.MOUSEBUTTONDOWN:
            if event.button == 1:
                if plyr.shotsLeft > 0:
                    plyr.shoot()
                    plyr.shotsLeft -= 1

    #text shadows
    shotsleft_text = font.render(f"{plyr.shotsLeft}", True, (200, 200, 200))
    screen.blit(shotsleft_text, (1/4 * screenWidth - 30, screenHeight/2 - 55))

    score_text = font.render(f"{plyr.score}", True, (200, 200, 200))
    screen.blit(score_text, (3/4 * screenWidth - 15, screenHeight/2 - 55))

    #text front
    shotsleft_text = font.render(f"{plyr.shotsLeft}", True, (255, 255, 255))
    screen.blit(shotsleft_text, (1/4 * screenWidth - 30, screenHeight/2 - 60))

    score_text = font.render(f"{plyr.score}", True, (255, 255, 255))
    screen.blit(score_text, (3/4 * screenWidth - 15, screenHeight/2 - 60))

    #spawn clays
    clayCurrCooldown += 1
    if clayCurrCooldown > clayReqCooldown:
        clayCurrCooldown = 0
        clayReqCooldown = random.uniform(0.7, 1.5) * 60
        spawnClay()

    #update player
    plyr.physicsUpdate()
    plyr.draw()

    #update clays
    for i in range(len(clays)):
        clays[i].physicsUpdate()
        clays[i].draw()

    #remove dead clays
    clays = [clay for clay in clays if not clay.isDead and clay.pos[1] < screenHeight]

    #check for death
    if plyr.pos[1] > screenHeight + 500:
        running = False

    #displayFPS(screen, 20)
    pygame.display.flip()
    clock.tick(60)

pygame.quit()